[package]
name = "flowgen"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "flowgen"
path = "src/lib.rs"

[dependencies]
tonic = { version = "0.10.2", features = ["tls-roots"] }
