[package]
name = "flowgen"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"
prost-types = "0.12.3"
reqwest = { version = "0.11.23", features = ["json", "stream"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = { version = "1.0.111" }
tonic = "0.10.2"
bytes = "1.5.0"
tokio = "1.35.1"
futures-util = "0.3.30"
tokio-stream = "0.1.14"
tokio-util = "0.7.10"
futures = "0.3.30"

[build-dependencies]
tonic-build = "0.10.2"
prost-build = "0.13.1"
