{{- $worker := index .Values "flowgen-worker" -}}
{{- if and $worker.enabled $worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "flowgen-worker.fullname" . }}
  labels:
    {{- include "flowgen-worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "flowgen-worker.fullname" . }}
  minReplicas: {{ $worker.autoscaling.minReplicas }}
  maxReplicas: {{ $worker.autoscaling.maxReplicas }}
  metrics:
    {{- if $worker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $worker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $worker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $worker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
