{{- $worker := index .Values "flowgen-worker" -}}
{{- if and $worker.enabled $worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowgen-worker.serviceAccountName" . }}
  labels:
    {{- include "flowgen-worker.labels" . | nindent 4 }}
  {{- with $worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
