{{- $worker := index .Values "flowgen-worker" -}}
{{- if $worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgen-worker.fullname" . }}
  labels:
    {{- include "flowgen-worker.labels" . | nindent 4 }}
spec:
  type: {{ $worker.service.type }}
  selector:
    {{- include "flowgen-worker.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ $worker.service.port }}
    targetPort: http
    protocol: TCP
    name: http
{{- end }}
