[workspace]
members = ["flowgen"]
resolver = "2"
exclude = [".cargo"]

[workspace.package]
version = "0.0.1"
authors = ["CONNVE"]
license = "MIT"
edition = "2021"
publish = false

[workspace.dependencies]
handlebars = { version = "6.3.0" }
arrow-json = { version = "54.0.0" }
chrono = { version = "0.4.39" }
tracing = { version = "0.1" }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = { version = "1.0.111" }
tokio = { version = "1.35.1" }
thiserror = { version = "1.0.63" }
futures-util = { version = "0.3.30" }
futures = { version = "0.3.30" }
arrow = { version = "54.0.0" }
reqwest = { version = "0.12.11" }
