[workspace]
members = ["flowgen"]
resolver = "2"
exclude = [".cargo"]

[workspace.package]
version = "0.0.1"
authors = ["CONNVE"]
license = "MIT"
edition = "2021"
publish = false

[workspace.dependencies]
handlebars = "6.3.0"
arrow-json = "54.0.0"
