[workspace]
members = ["flowgen", "examples"]
resolver = "2"
exclude = [".cargo"]

[workspace.dependencies]
flowgen_salesforce = { path = "components/salesforce" }
flowgen_google = { path = "components/google" }
flowgen = { path = "flowgen" }

[workspace.package]
version = "0.0.1"
authors = ["CONNVE"]
license = "MIT"
edition = "2021"
publish = false
